兼容 Xcode9
huangxuan518/HXPackRobot pull request #14
Opened 2017-10-11 04:14 UTC by moonclock

exportOptionsPlist.plist中需要新增加键值,如提交中所示.
另:请更新一下 github 页面说明,增加一下对应配置教程,谢谢!

2017-12-08 09:52 UTC, huangxuan518 commented
合并

2017-12-08 10:00 UTC, huangxuan518 reviewed
111

2017-12-08 10:05 UTC, huangxuan518 commented
新的

2017-12-08 10:09 UTC, huangxuan518 reviewed
111111111

2017-12-08 10:10 UTC, huangxuan518 requested changes
11111111111111111111

2017-12-08 10:25 UTC, moonclock commented
没 Merge 成功啊 😂

2017-12-11 06:22 UTC, huangxuan518 requested changes
11111111111

2017-12-11 07:00 UTC, closed without merging